model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    monitor: "val_rec_loss"
    embed_dim: 3
    n_embed: 8192
    image_key: masked_image
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
#      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      ch_mult:
        - 1
        - 2
        - 4
      num_res_blocks: 2
#      attn_resolutions: [16]
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
#    batch_size: 5
#    num_workers: 8
    batch_size: 2
    num_workers: 0
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /home/zwb/zwb/code/0531/ldm_thin/datasets/celeba-hq-dataset/train_shuffled_w.flist
        size: 256
        mask_mode: m7   # 'hybrid' 'center' 'ThinStrokes',  'MediumStrokes', 'ThickStrokes', 'Every_N_Lines', 'Completion', 'Expand', 'Nearest_Neighbor', m3, m5, m7
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /home/zwb/zwb/code/0531/ldm_thin/datasets/celeba-hq-dataset/val_shuffled_w.flist
        size: 256
        mask_mode: center   # 'hybrid' 'center' 'ThinStrokes',  'MediumStrokes', 'ThickStrokes', 'Every_N_Lines', 'Completion', 'Expand', 'Nearest_Neighbor', m3, m5, m7


